### ISSUE TITLE
Invalid frame header

### ISSUE THREAD

**Issue by maheshnayer** [gobwas/ws#100]
Hi, I have a websocket client connecting to a go websocket server. I'm occasionally receiving the error invalid frame header in the browser. On checking the message received from the server, I can see this special character, ï
This message is never sent by the server in terms of logic. So I assume this is sent internally
Since this is not a proper response byte, I assume the websocket client disconnects the connection. The server logs the error with 1002 Websocket Protocol Error without too many details
What is causing this issue and how can I resolve it?

**Comment by maheshnayer** [comment]
Hi. I've found the issue. This happens when the same conn object does concurrent write. This results in malformed data sent to the client. Ideally a panic should be raised in such scenario. Hope this helps someone else

**Comment by Mutated1994** [comment]
#133 

Me too.
