### ISSUE TITLE
[Question] is the wsutil's readData function calling the read system call multiple times?

### ISSUE THREAD

**Issue by ytkang** [gobwas/ws#103]
wsutil -> readData() is like this,
```
NextFrame()    -------> read header from fd
...
ioutil.ReadAll(&rd) --> read data from fd
```

It seems calling system call read two times, actually 3 times(NextFrame will have 2 times). right?

If then, is there a plan to add read buffer to wsutil?
or just fine? Is reading from socket directly multiple times same with using buffer?

\+ It seems hard to implement custom read buffer. because ws.ReadHeader() seems not designed for read buffer.

**Comment by gobwas** [comment]
Hi @ytkang, `wsutil` should work fine with `bufio.Reader` as the source.
