### ISSUE TITLE
Is compression supported?

### ISSUE THREAD

**Issue by snowinszu** [gobwas/ws#108]

**Comment by cristaloleg** [comment]
AFAIR no, there is an unfinished PR with a flate compression https://github.com/gobwas/ws/pull/58

**Comment by snowinszu** [comment]
Hope support soon :)

**Comment by gobwas** [comment]
Hi @snowinszu, you can try to use one from the linked PR above. It passes Autobahn tests and seems working. Earlier feedback on API is welcome!

**Comment by gobwas** [comment]
I'm closing this for now in hope to continue discussion in the [PR](https://github.com/gobwas/ws/pull/118).
