### ISSUE TITLE
clean close conn

### ISSUE THREAD

**Issue by ezinall** [gobwas/ws#109]
Сергей, добрый день.

При закрытии соединения через:
`if err := ws.WriteFrame(*conn, ws.NewCloseFrame(ws.NewCloseFrameBody(ws.StatusNormalClosure, "Server shutdown"))); err != nil {
	fmt.Println(err)
}`
После этого читаю через wsutil.ReadClientData(conn) и закрываю соединение conn.Close(), но на стороне клиента все равно происходит обрыв соединения, а не чистое закрытие.
Как чисто закрыть соединение?

**Comment by gobwas** [comment]
Добрый день, @ezinall!
На другом конце тоже нужно отправлять CloseFrame.
