### ISSUE TITLE
usage example of web socket clients in the README.md

### ISSUE THREAD

**Issue by nhooyr** [gobwas/ws#11]
As of now, the usage examples in the README.md are only about the server. Many people such as myself are also writing web socket clients so it would be nice to have a simple example to get us started.

**Comment by corpix** [comment]
Does anybody figured out the correct way to write a client with this package?

**Comment by corpix** [comment]
This package API reminds me gorilla/websocket, here is my naive example of client https://github.com/corpix/go-playground/tree/master/at-2017-09-12-153616

Feel free to create an issue in case you will find something strange :)

**Comment by gobwas** [comment]
Hi @corpix! Thanks for the example.

Note that while I was writing another example (CLI client for WebSocket chat), I have discovered a [rare bug](https://github.com/gobwas/ws/issues/19), which leads to missing some bytes of incoming frames.

Feel free to propose another solution.

**Comment by di3663** [comment]
may be someone need this
```
package main

import (
	"context"
	"fmt"
	"sync"
	"time"

	"github.com/gobwas/ws"
	"github.com/gobwas/ws/wsutil"
)

func test(i int, wg *sync.WaitGroup) {
	conn, _, _, err := ws.DefaultDialer.Dial(context.Background(), "ws://127.0.0.1:2000/")
	defer wg.Done()
	if err != nil {
		fmt.Printf("%d can not connect: %v\n", i, err)
	} else {
		fmt.Printf("%d connected\n", i)
		msg := []byte("OK+OK")
		err = wsutil.WriteClientMessage(conn, ws.OpText, msg)
		if err != nil {
			fmt.Printf("%d can not send: %v\n", i, err)
			return
		} else {
			fmt.Printf("%d send: %s, type: %v\n", i, msg, ws.OpText)
		}

		msg, op, err := wsutil.ReadServerData(conn)
		if err != nil {
			fmt.Printf("%d can not receive: %v\n", i, err)
			return
		} else {
			fmt.Printf("%d receive: %s，type: %v\n", i, msg, op)
		}

		time.Sleep(time.Duration(3) * time.Second)

		err = conn.Close()
		if err != nil {
			fmt.Printf("%d can not close: %v\n", i, err)
		} else {
			fmt.Printf("%d closed\n", i)
		}
	}
}

func main() {
	var wg sync.WaitGroup
	for i := 0; i < 7000; i++ {
		wg.Add(1)
		go test(i, &wg)
	}
	wg.Wait()
}
```

**Comment by nhooyr** [comment]
Going to close as it has been a long time and I'm not sure if this is relevant anymore.
