### ISSUE TITLE
Using values from req.uri to extract user data while doing upgrade to be used later

### ISSUE THREAD

**Issue by rahultripathidev** [gobwas/ws#112]
since it is not possible to pass custom headers while using the default websocket apis on browsers ([https://github.com/whatwg/html/issues/3062](https://github.com/whatwg/html/issues/3062)) , according to me the uri should be available to extract query params while doing a direct upgrade from tcp to websocket . The OnRequest method allows me to perform checks on the uri but it is not available for further use . So is it possible to access uri ?  I tried this 

`func (u Upgrader) Upgrade(conn io.ReadWriter) (hs Handshake, uri string, err error) `
and then using it `hs, uri ,err := ws.Upgrade(conn)` 

but is it the right way to do it ?

**Comment by gobwas** [comment]
Hi @rahultripathidev,

The whole `Upgrader` API was designed be able used per each upgrade:

```
func upgrade(conn net.Conn) {
    var query url.Values
    u := ws.Upgrader{
        OnRequest: ... // Extract uri values here.
    }
    u.Upgrade(conn)
}
```

**Comment by rahultripathidev** [comment]
oh ! got it ... feels stupid to ask such things . thanks @gobwas

**Comment by gobwas** [comment]
No worries, @rahultripathidev 👍
