### ISSUE TITLE
`set-cokie` header

### ISSUE THREAD

**Issue by Pantani** [gobwas/ws#119]
Hello @gobwas, 
Is there a way to pass an HTTP header into a request or only in the handshake?
I want to use the `set-cookie` header after the user is authenticated, is it possible?

**Comment by nerg4l** [comment]
Once the WebSocket connection established the connection is upgraded from a regular HTTP request to an open TCP socket. This means you cannot set a header. You can only use `Set-Cookie` header before the upgrade.

**Comment by gobwas** [comment]
Hello @Pantani, yeah, as @nerg4l suggested, it's possible only during the HTTP handshake. E.g. after your user is authenticated, you can send HTTP upgrade request to a server to start using WebSockets. 

Closing this for now.

**Comment by Pantani** [comment]
thanks!!
