### ISSUE TITLE
Package isn't working

### ISSUE THREAD

**Issue by kerak19** [gobwas/ws#12]
Can't even run any of the examples.

```
# github.com/gobwas/ws
../../../../github.com/gobwas/ws/client.go:249: too many arguments to return
	have (*bufio.Reader, int)
	want (*bufio.Reader)
../../../../github.com/gobwas/ws/server.go:333: multiple-value pbufio.GetReader() in single-value context
```

**Comment by gobwas** [comment]
Hi @kerak19!
Sorry for downtime. You've catch me on refactoring of `github.com/gobwas/pool` code. 
Now it must work. 🍻

**Comment by kerak19** [comment]
Yeah, no problem. But not building code on master? Better be more cautious next time :p
