### ISSUE TITLE
Address TODO: add max frame size limit

### ISSUE THREAD

**Issue by agnivade** [gobwas/ws#126]
Hi there,

Thanks for this great library. I am looking to use it to migrate from gorilla to this for [Mattermost](https://github.com/mattermost/mattermost-server) server.

However, without a max frame size limitation, it would not be possible for this to be used in production.

I am willing to send a PR myself to address this if anybody isn't actively working on it already. Wanted to create an issue first to check that. Is there any additional context I should keep in mind if I want to implement it?

**Comment by gobwas** [comment]
Hey @agnivade!

Thank you for a good feedback!

Feel free to start working on that, I'm not aware if anyone else wanted to do it.
Probably there is not much to do -- at the first glance I think the `wsutil.Reader.NextFrame()` implementation must be affected to perform checks of frame size against `Reader.MaxFrameSize` (or something like that) option.

**Comment by agnivade** [comment]
Thanks, I'll take a look.

**Comment by gobwas** [comment]
Closed by #127
