### ISSUE TITLE
86 B/op   1 allocs/op?

### ISSUE THREAD

**Issue by hellochenwang** [gobwas/ws#128]
```
$ go test -bench=Gobwas -benchmem -benchtime=10s
Benchmark1000GobwasClientsPer10Messages-8         98497042   106 ns/op        86 B/op   1 allocs/op
Benchmark1000GobwasClientsPer100Messages-8      1000000000    13.4 ns/op       8 B/op   0 allocs/op
Benchmark1000GobwasClientsPer1000Messages-8     1000000000     1.19 ns/op      0 B/op   0 allocs/op
Benchmark100GobwasMsgsPerConn-8                  833576667    14.6 ns/op       8 B/op   0 allocs/op
Benchmark1000GobwasMsgsPerConn-8                1000000000     1.46 ns/op      0 B/op   0 allocs/op
Benchmark10000GobwasMsgsPerConn-8               1000000000     0.156 ns/op     0 B/op   0 allocs/op
Benchmark100000GobwasMsgsPerConn-8              1000000000     0.0262 ns/op    0 B/op   0 allocs/op
```

Source: https://github.com/dgrr/fastws/

**Comment by cristaloleg** [comment]
(Quick) look suggests that this is caused by `readRequest` from stdlib, which is used in all libs except `fastws`.

**Comment by gobwas** [comment]
Hey @hellochenwang! Thank you for sharing. I'm not sure how that benchmark is done, but I beleive it uses `ws/wsutil` which is not as efficient by intention -- it provides more easy abstractions over lower level `ws` package. So if you want to control every allocation you should definitely should use just `ws`.

Also, I don't think that project readme is fair enough by saying this:
> Other WebSocket packages does not allow concurrent Read/Write operations and does not provide low level access to WebSocket packet crafting.

Based on what I've said above, `ws` package perfectly do provide low level access for WebSocket packet crafting.
