### ISSUE TITLE
flate.Reader and double buffering

### ISSUE THREAD

**Issue by ligser** [gobwas/ws#130]
Hello! Thanks for a great lib.

I try to use pre-released `wsflate` package and see a slight caveat when try to re-use decoders.
As I can see the `flate.decompressor` (default `flate.Reader` impl) try to prevent double buffering if it possible and when I call `Reset`, or `NewReader` it calls a small func that called [`makeReader`](https://github.com/golang/go/blob/1901853098bbe25a1bbedc0ee53c6658d754151e/src/compress/flate/inflate.go#L749). That func will check if passed `io.Reader` also implements `flate.Reader` and can be used as-is without buffering.
If it not - it will allocate `bufio.NewReader` with `defaultBufSize` (4kb) slice and wraps passed reader into it.
When I work with `byte.Reader` on my side — it can rely to that behavior and if I pass `bytes.Reader` I avoid double buffering (since it already implements `flate.Reader`). But in `wsflate` there is [`suffixReader`](https://github.com/gobwas/ws/blob/852c4b99d6fb14fcfd7e765d64f59062bd517d33/wsflate/cbuf.go#L60) that wraps passed `io.Reader` and erase its `ReadByte` method when [`Reader.Reset` ](https://github.com/gobwas/ws/blob/master/wsflate/reader.go#L49) was called.
It might be great to have a way to prevent double buffering here and if I already pass buffered reader here - prevent it from being wrapped in `flate.decompressor`.

**Comment by gobwas** [comment]
Hey @ligser!

Thanks for reporting and sorry for me missing this out. I will delve into it on a weekend to see how can I improve it! 👍🏻
