### ISSUE TITLE
ws.UpgradeHTTP should only return exported error types

### ISSUE THREAD

**Issue by simonmittag** [gobwas/ws#136]
Hi!

I'm using `ws.upgradeHTTP()` inside our proxy server project (see: https://github.com/simonmittag/j8a/blob/56/websockethandler.go#L85 )to leverage the existing HTTP request, then upgrade. This works well for the most part, **except when upgrade returns unexported errors**. The below won't compile:

```
dwnCon, _, _, dwnErr := ws.UpgradeHTTP(proxy.Dwn.Req, proxy.Dwn.Resp.Writer)
     if dwnErr != nil {
     wsRejConErr, wrj:= dwnErr.(*ws.rejectConnectionError)
}
``` 

I need access to the HTTP error code response that was sent by HTTPUpgrader.Upgrade()

Can you please export `ws.RejectConnectionError` in an upcoming release?

Thanks,

Simon

PS: if this is not an option, do you have an alternative proposed solution i.e writing a custom HTTP upgrader? I was not able to find a good example of this

**Comment by gobwas** [comment]
Hi @simonmittag, do you think it would be sufficient to provide `ws.UpgradeRejectedError` interface (or something named better) which will have just `StatusCode() int` method? I'm not sure it's a right way to just export `ws.rejectConnectionError`. Maybe I'm wrong with it though. 

@cristaloleg what do you think?

I'm not sure because all the fields are actually optional for the error. Moreover, its `header` field can be written to the wire and thus be empty.

**Comment by simonmittag** [comment]
> Hi @simonmittag, do you think it would be sufficient to provide `ws.UpgradeRejectedError` interface (or something named better) which will have just `StatusCode() int` method? I'm not sure it's a right way to just export `ws.rejectConnectionError`. Maybe I'm wrong with it though.

thanks for looking into this! An interface to access status code would be great.

**Comment by cristaloleg** [comment]
@gobwas I think exposing error type is a good thing. We don't overload API with additional entity (I mean `UpgradeRejectedError` interface) and also exposing error type is a pretty common thing (`error` is an interface itself, so we would like to match `error` to a specific type).

Objections?

**Comment by gobwas** [comment]
@cristaloleg I think it's the same in terms of number of entities we add to the API: it's either an interface or struct. If we export the struct, I worry about its fields: for example, the `r.code` field -- should we export it as is? It can be not set by `RejectConnectionError()` constructor... 🤔

**Comment by simonmittag** [comment]
FYI I created a temporary fork of ws, exporting the error type and adding `Code()`. See: https://github.com/simonmittag/ws/blob/master/errors.go

This is a workaround until I can achieve the same using the original project.
