### ISSUE TITLE
Can't catch a user disconnect event

### ISSUE THREAD

**Issue by monopollly** [gobwas/ws#15]
Hi, its an awesome package, thank you!
But I can't catch a disconnect event.
I try to get OpClose, but its not working...

How to catch it and remove user from list?
thanks

**Comment by monopollly** [comment]
got it)

**Comment by gobwas** [comment]
Hi @monopollly!

Note that not all clients will send OpClose frame. So it is better rely on `io.EOF` error when reading from connection.
