### ISSUE TITLE
MaxReaderSize for wsutil.ReadClientData

### ISSUE THREAD

**Issue by ilovesusu** [gobwas/ws#151]
Should you add a max read limit to wsutil.ReadClientData, otherwise, it's hard to use it in production

**Comment by enkeyz** [comment]
You can just use https://pkg.go.dev/io#CopyN .

**Comment by Deleplace** [comment]
That would be useful indeed. It's mostly about leveraging [Reader.MaxFrameSize](https://github.com/gobwas/ws/blob/master/wsutil/reader.go#L54)

**Comment by cristaloleg** [comment]
Can it be solved with https://pkg.go.dev/io#LimitedReader ? as a param to `wsutil.ReadClientData`

**Comment by Deleplace** [comment]
Yes actually MaxFrameSize is not what we want here.   

LimitedReader is a better candidate.

**Comment by cristaloleg** [comment]
Looks like the issue is resolved, closing. Feel free to reopen, thanks.
