### ISSUE TITLE
Client-side example?

### ISSUE THREAD

**Issue by klauspost** [gobwas/ws#179]
Hi!

Sorry for the probably stupid question, but I don't really see how to do a clientside connection to a remote. I see some proxy examples, but they appear to mostly be forwarding requests.

## Background

I am implementing a two-way connection between servers that should eventually be able to mux multiple message types. This seems like a great match, since it allows me to control allocations much better than the alternatives.

There is however no "server" and "client" - either can initiate the connection and I have a mechanism for resolving collisions. Do I simply dial and use the connection from that with no direct actions to upgrade on the client?

A client-side example would be great, since it isn't very obvious to me what I should do.

Thanks for the great package. Looking forward to diving deeper into it.

**Comment by cristaloleg** [comment]
Hey, thanks for the reminder. I was slow on that last month. Will publish a PR in the next few days. In short:

```go
conn, _, _, err := ws.DefaultDialer.Dial(context.Background(), "ws://127.0.0.1:9000")
if err != nil {
	panic(err)
}

for {
	err := wsutil.WriteClientMessage(conn, ws.OpText, []byte{"my message"})
	if err != nil {
		panic(err)
	}

	time.Sleep(time.Second)

	msg, op, err := wsutil.ReadServerData(conn)
	if err != nil {
		panic(err)
	}
}
```

**Comment by klauspost** [comment]
Thanks a bunch. Should be enough to get started.

**Comment by klauspost** [comment]
If you are still reading, I presume that read/write can be in separate goroutines like `net.Conn` promises.

**Comment by cristaloleg** [comment]
For simplicity I left them in 1 loop.
