### ISSUE TITLE
ReadFrame maxs out at 4096 lengths

### ISSUE THREAD

**Issue by suffz** [gobwas/ws#183]
looking for a work around.

**Comment by cristaloleg** [comment]
Any details? Reproducer, version, whatever.

**Comment by suffz** [comment]
```go
if payload, err := ws.ReadFrame(wsconn); err == nil {
```

Once the payload.Payload gets to around 4096 it maxs out and no new data is sent through afaik. im jw cause im using this for a websocket and the data can get up there and some of it is being cut off.

**Comment by om26er** [comment]
@suffz I think we need a real test case that can be used to reproduce the problem. Otherwise there definitely isn't going to be a workaround

**Comment by cristaloleg** [comment]
Yeah, but it's just a default, the real usage is here https://github.com/gobwas/ws/blob/fe40e5d87b2c7a74c6a202027ed76789fb3647fd/dialer.go#L58

Try to set higher value to these fields, this should help.

**Comment by suffz** [comment]
I could try, but I'm making my own ws connection and using that tls conn with this library to send / recv payloads. 

The built in dialer wouldn't do much in this regard no?

**Comment by cristaloleg** [comment]
Please, share the results.

**Comment by suffz** [comment]
Alright, will do some tests after work.
