### ISSUE TITLE
Any example for using this library with `gnet`?

### ISSUE THREAD

**Issue by spy16** [gobwas/ws#201]
I am trying to use `gobwas/ws` with `https://github.com/panjf2000/gnet` library in an attempt to build a high-performance websocket server.

I am running into `io.ErrShortBuffer` error under two cases:

1. When client sends a message with size larger than the max-read-buffer set on the gnet server.
2. When client sends a PING message.

I don't have deep understanding of the websocket protocol internals, but I believe this happens due to the continuation & fragmented frames? I found [this reference](https://github.com/gnet-io/gnet-examples/blob/v2/websocket/server/codec.go) but it's bit unclear .. 

Are there any other examples to use `gobwas/ws` to use with a model like `gnet`? I believe, what I need here is to use a buffered reader in between instead of directly passing the `gnet.Conn` to the `wsutil` / `ws` functions.

**Comment by cristaloleg** [comment]
Hey, no idea about `gnet`, maybe @panjf2000 has some ideas.

**Comment by ehsannm** [comment]
I have created a very fast and modular framework and is used in production in our company. You can check how i used gnet an ws together. 
Http://github.com/clubpay/ronykit 


The related code is in std/gateways/fastws

**Comment by spy16x** [comment]
@ehsannm Thank you! This is really helpful.

Have you tried sending a websocket message that is larger than the `MaxReadBufCap` set in `gnet` though? I think your implementation resolves the first issue since the part of reading all the control frames is in a loop.

But once you get a text/binary payload frame, if the frame size is bigger than the `MaxReadBufCap` set on gnet, I believe, you would also run into the short-buffer error. For example, if you set this to 4096, the websocket message can only be 4088 bytes (the remaining 8 bytes are used for the frame header)

**Comment by spy16** [comment]
@ehsannm Thank you! This is really helpful.

Have you tried sending a websocket message that is larger than the MaxReadBufCap set in gnet though? I think your implementation resolves the first issue since the part of reading all the control frames is in a loop.

But once you get a text/binary payload frame, if the frame size is bigger than the MaxReadBufCap set on gnet, I believe, you would also run into the short-buffer error. For example, if you set this to 4096, the websocket message can only be 4088 bytes (the remaining 8 bytes are used for the frame header)

**Comment by ehsannm** [comment]
@spy16 thanks for the point, i did write a test in the `testenv` package and realized that you were right about the issue, i fixed it and pushed. You can check it again.

**Comment by spy16x** [comment]
Thanks, I will check this out. 

I will also close this issue since it's more related to the source reader itself than this package.

**Comment by spy16** [comment]
Thanks, I will check this out. 

I will also close this issue since it's more related to the source reader itself than this package.
