### ISSUE TITLE
Can I use it to develop high-load Socket (non WebSocket)  server?

### ISSUE THREAD

**Issue by LeMoussel** [gobwas/ws#25]
Hi,

I developed high-load Socket (non WebSocket)  server with Go. 
Can I use `ws` to reduce the load on the servers?

**Comment by gobwas** [comment]
Hi @LeMoussel!

Sorry, I do not understand how can you reduce the load on the servers with `ws` package if you do not use WebSockets in your app?

**Comment by LeMoussel** [comment]
OK. Thanks.
Rem : Currently, netpool is implemented only for Linux.

**Comment by gobwas** [comment]
For Linux and Darwin ;-)
If you want, you can implement it for Windows. =)
