### ISSUE TITLE
in ws.Upgrader, retrieve cookie?

### ISSUE THREAD

**Issue by joesonw** [gobwas/ws#31]
I see the example code given in Readme did check for cookies. But is there anyway to return the cookie value when calling `upgrader.Upgrade`? Otherwise it would be meaningless to validate the cookie other than prevent unknown requests.

**Comment by gobwas** [comment]
Hi @joesonw!
Sorry I did not understand you correctly with "_Otherwise it would be meaningless to validate the cookie other than prevent unknown requests._"? Could you explain me what problem do you want to solve with returned cookie values?

**Comment by joesonw** [comment]
@gobwas thanks for the reaching back. Is there a way to retrieve cookie value(https://github.com/gobwas/ws/blob/master/README.md#L285)  or any other header values at/after upgrading connection,

**Comment by joesonw** [comment]
@gobwas  thanks for the reaching back. Is there a way to retrieve cookie value(parsed at https://github.com/gobwas/ws/blob/master/README.md#L285) or any other header values at/after upgrading connection.

**Comment by gobwas** [comment]
Yes, you are right about new upgraders. If you use the `u := ws.Upgrader{...}` it would be placed on the stack, and no additional allocation will be made. Allocations will occur only when you will *copy* the cookie or header value which are interesting for your app for further use.

Why it would be against the zero-copy idea? If you want to use some request bytes there is no chance to get rid of a copying them somewhere in memory =)

**Comment by gobwas** [comment]
@joesonw could I close your issue now? )

**Comment by joesonw** [comment]
@gobwas sorry for the delayed response. I ended up using a pool of upgraders to store custom cookie values.

**Comment by gobwas** [comment]
@joesonw did you benchmarked the behavior with allocation on stack? It seems to me that pooling Upgraders does not make sense?

**Comment by joesonw** [comment]
@gobwas I haven't yet put all things together. I wasn't sure about the allocation cost of upgraders, so I took a pool for 'presumed' better memory usage. Hence I need to access values in the headers, I have to store it somewhere in Upgraders. I came up with a struct that extends Upgrader and store values in the same struct. These values then can be accessed after upgraded.

**Comment by gobwas** [comment]
@joesonw got this. Thanks for the details. 👍
