### ISSUE TITLE
Upgrade Error : Bad Connection Header

### ISSUE THREAD

**Issue by raja3000** [gobwas/ws#36]
Need help

I am using chat application under ws-example and also tried other example applications.

When I try to connect to the websocket directly (not through proxy),  getting "Upgrade Error : bad "Connection" header"

I dont want to use proxy in my case. Please suggest

**Comment by gobwas** [comment]
Hi @raja3000,
How do you connecting to your WebSocket server?

**Comment by gobwas** [comment]
@raja3000 🏓

**Comment by gobwas** [comment]
@raja3000 will close it for now, when you get back you can provide more info and reopen the issue. Thanks =)

**Comment by raja3000** [comment]
Sorry, I could not reply as I was travelling.. 

To connect to WebSocket server, I was trying to open http://localhost:3333 or ws://localhost:333 in the browser. 

Please suggest what is the right way to connect.

**Comment by gobwas** [comment]
To open a WebSocket connection from browser you should use appropriate [JavaScript API](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket).

```js
var ws = new WebSocket("ws://localhost:3333");
```
