### ISSUE TITLE
Godoc API is wrong about UpgradeHTTP

### ISSUE THREAD

**Issue by squarism** [gobwas/ws#38]
At [the godoc main page](https://godoc.org/github.com/gobwas/ws):

```
http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
	  conn, err := ws.UpgradeHTTP(r, w, nil)
  })
```

Two variables are returned but looks like current source returns 4.  It should be:
`conn, _, _, err := ws.UpgradeHTTP(r, w, nil)`

**Comment by gobwas** [comment]
Hi @squarism! Thanks for the catch. Fixed.
