### ISSUE TITLE
Does this library support compression?

### ISSUE THREAD

**Issue by gauthamns** [gobwas/ws#41]
Is there a support for compression in ws?

**Comment by gobwas** [comment]
Hi @gauthamns!

Technically it supports any plugins over I/O streaming – this library was intended for such extensibility. But there are no any concrete compression implementation inside `ws` or `ws/wsutil` packages.

You could take any implementation that support go's standard `i/o` interfaces and streaming.

**Comment by gauthamns** [comment]
Many thanks for the response. Will try and revert back if I need any help.

**Comment by gobwas** [comment]
Hi @gauthamns! Do you tried something? )

**Comment by gobwas** [comment]
Closing this due to this [PR](https://github.com/gobwas/ws/pull/118).
