### ISSUE TITLE
Using ws.{Reader,Writer} with a persistent JSON encoder/decoder

### ISSUE THREAD

**Issue by shazow** [gobwas/ws#46]
Hi there, I'm trying to figure out if it's possible to use this library with a persistent JSON encoder and decoder as the messaging interface (without remaking the encoder/decoder with each message).

With other libraries, I'd typically do something like:

```go
func (srv *Server) Join(conn *websocket.Conn) error {	 
	decoder := json.NewDecoder(conn)	
	encoder := json.NewEncoder(conn)	
 	
	for {
		// Decode next message
		msg := Message{...}
		if err := decoder.Decode(&msg); err != nil {
			return err
		}
		...
		if err := encoder.Encode(&Response{...}); err != nil {
			return err
		}
	}
}
```

Is it possible to do something similar with ws? Every example I find, it's making a new encoder/decoder with each message, which I'm hoping to avoid.

Here's what I have so far:

```go
// Join runs the event loop for a connection, should be run in a goroutine.
func (srv *Server) Join(conn net.Conn) error {
	if _, err := ws.ReadHeader(conn); err != nil {
		return err
	}

	r := wsutil.NewReader(conn, ws.StateServerSide)
	decoder := json.NewDecoder(r)

	w := wsutil.NewWriter(conn, ws.StateServerSide, ws.OpText)
	encoder := json.NewEncoder(w)

	for {
		// Write buffer
		if err = w.Flush(); err != nil {
			return err
		}
		// Prepare for the next message
		if _, err = r.NextFrame(); err != nil {
			return err
		}
		// Decode next message
		msg := Message{}
		if err := decoder.Decode(&msg); err != nil {
			return err
		}
		...
		if err := encoder.Encode(&Response{...}); err != nil {
			return err
		}
	}
}
```

But I'm getting errors like `ErrProtocolControlNotFinal`.

Does the design of `ws` disallow using it in this manner, or am I missing something?

**Comment by gobwas** [comment]
Hi,

> Hi there, I'm trying to figure out if it's possible to use this
> library with a persistent JSON encoder and decoder as the messaging
> interface (without remaking the encoder/decoder with each message).

Yes, the existence of `wsutil` package is intended exactly for that.

> Here's what I have so far:

Why there is a first line of `Join` implementation with
`ws.ReadHeader()` call? May be this is the reason you receiving error on
reading messages in a loop.

Could you try something like this:

```go
// Join runs the event loop for a connection, should be run in a goroutine.
func (srv *Server) Join(conn net.Conn) error {
	var (
		r = wsutil.NewReader(conn, ws.StateServerSide)
		w = wsutil.NewWriter(conn, ws.StateServerSide, ws.OpText)

		decoder = json.NewDecoder(r)
		encoder = json.NewEncoder(w)
	)
	for {
		if _, err = r.NextFrame(); err != nil {
			return err
		}
		var msg Message
		if err := decoder.Decode(&msg); err != nil {
			return err
		}
		var resp Response
		if err := encoder.Encode(&resp); err != nil {
			return err
		}
		if err = w.Flush(); err != nil {
			return err
		}
	}
}
```

**Comment by gobwas** [comment]
Could you try something like this:

```go
// Join runs the event loop for a connection, should be run in a goroutine.
func (srv *Server) Join(conn net.Conn) error {
	var (
		r = wsutil.NewReader(conn, ws.StateServerSide)
		w = wsutil.NewWriter(conn, ws.StateServerSide, ws.OpText)

		decoder = json.NewDecoder(r)
		encoder = json.NewEncoder(w)
	)
	for {
		if _, err = r.NextFrame(); err != nil {
			return err
		}
		var msg Message
		if err := decoder.Decode(&msg); err != nil {
			return err
		}
		var resp Response
		if err := encoder.Encode(&resp); err != nil {
			return err
		}
		if err = w.Flush(); err != nil {
			return err
		}
	}
}
```

**Comment by shazow** [comment]
Ah, that did the trick, thank you!

I think I added `ReadHeader` because I was getting some other unrelated error and I saw some examples had it and it made that particular error go away. It's difficult to 

Would you like for me to make a PR to add this pattern as an example anywhere?

**Comment by gobwas** [comment]
👍 

Actually, there is a very similar example in the **Usage** section of `ws/README.md`. But If you want, you could make it more focused on I/O abilities of `wsutil` package. 

Thanks!
