### ISSUE TITLE
Byte slice overwritten when upgrade 

### ISSUE THREAD

**Issue by shengery** [gobwas/ws#47]
Greetings, 

I found that, some websocket client library implementation will split the handshake info into several `packets` (typically two packets, means there are two tcp send syscalls during the first handshake packet. first line is `GET /uri HTTP/1.1 `, other part  is `HOST:some.domain\r\n.......`). This will cause the  byte slice overwritten by the latter  util.go: readLine funciton when the handshake info was delivered from client more than one packet.
The attachment is the test code, you may find the request.uri is not correct .

[wstest.zip](https://github.com/gobwas/ws/files/2026656/wstest.zip)

**Comment by gobwas** [comment]
Hi @shengery,
The `GET` line and the `Host: ...` header line is a really two different line. So what is a problem? Could you provide a simple go test for this?

**Comment by shengery** [comment]
The attachment is the test case.
I split the GET and Host into two calls, the request is :
 GET /ws http/1.1
Host : 127.0.0.1:8080
....
However, I set the OnRequest callback  in the wssrv.go 
`go 
var upgrader = ws.Upgrader{
	OnHeader: func(key, value []byte) (err error, code int) {
		k, v := string(key), string(value)
		log.Printf("got header key => value: %s=>%s\n", k, v)
		return
	},
	OnRequest: func(host, uri []byte) (err error, code int) {
		k, v := string(host), string(uri)
		log.Printf("got request host=>uri : %s=>%s\n", k, v)
		return
	},
}
`
The server output the result : `got request host=>uri : 127.0.0.1:8080=>: 1`, the uri was set during the first `readLine` in the upgrade function, and it's was  referenced to the bufio.Reader's  internal byte slice , which may be overwritten later when the readLine is called .

**Comment by gobwas** [comment]
Yeah, you are right – there is a bug and I can reproduce it by test. 
Will fix it soon, stay tuned 👍

**Comment by shengery** [comment]
In my fixed version, I add an extra memory copy in the ``` readLine ``` function  in the util.go
```go
func readLine(br *bufio.Reader) ([]byte, error) {
	var line []byte
	for {
		bts, err := br.ReadSlice('\n')
		if err == bufio.ErrBufferFull {
			// Copy bytes because next read will discard them.
			line = append(line, bts...)
			continue
		}

		// Avoid copy of single read.
		if line == nil {
			line = bts
		} else {
			line = append(line, bts...)
		}

		if err != nil {
			return line, err
		}

		// Size of line is at least 1.
		// In other case bufio.ReadSlice() returns error.
		n := len(line)

		// Cut '\n' or '\r\n'.
		if n > 1 && line[n-2] == '\r' {
			line = line[:n-2]
		} else {
			line = line[:n-1]
		}
               l := make([]byte, len(line))
                copy(l, line)
		return l, nil
	}
}
```
This will increase the memory allocation, is there any better option?

**Comment by gobwas** [comment]
Hi @shengery. Could you check the latest version? It just splits `OnRequest` callback into `OnRequest(uri)` and `OnHost(host)` callbacks.
