### ISSUE TITLE
gobwas/pool dependency issue

### ISSUE THREAD

**Issue by zdebra** [gobwas/ws#49]
Right now, `dep` will resolve `gobwas/pool` dependency in a way that latest (and used) version is `e294a5482d9a8523f8e6b2744ea2185083c838af` which is currently 2 commits back. The reason is because it is last tagged version. 

Current version of `gobwas/ws` with older version of `gobwas/pool` wont compile because of breaking change.

The best solution is to just add tag to latest commit in `gobwas/pool`.

**Comment by gobwas** [comment]
Hi @zdebra! 
Thank you for the issue. I will tag it during closest few hours. 🚀

**Comment by gobwas** [comment]
@zdebra could you try it? It must work now.
