### ISSUE TITLE
Write/Read Deadline does not work ?

### ISSUE THREAD

**Issue by ehsannm** [gobwas/ws#57]
I tried conn.SetWriteDeadline but it does not work. How can i make it using gobwas ?

**Comment by gobwas** [comment]
Hi @ehsannm. How do you check it? Basically you need to fill up os tcp read buffer on the other side to get the EAGAIN errors inside `conn.Write()` call. And then, if the other side will still not be reading, your `Write()` call will return error.

**Comment by gobwas** [comment]
Or, the more simple example is just:
```go
conn.SetWriteDeadline(time.Now())
time.Sleep(time.Millisecond)
conn.Write([]byte("hello, world!"))
```
