### ISSUE TITLE
TLS support

### ISSUE THREAD

**Issue by pokerman79** [gobwas/ws#59]
Is it possible to use this library over SSL, any attempt to use over ssl returns error in netpool
panic: "could not get file descriptor"

Code example
cer, err := tls.LoadX509KeyPair("./etc/cert.crt", "./etc/cert.key")
	if err != nil {
		panic(err)
	}
config := &tls.Config{Certificates: []tls.Certificate{cer}}
	ln, err := tls.Listen("tcp", "0.0.0.0:443", config)
	if err != nil {
		panic(err)
	}
	acceptDesc := netpoll.Must(netpoll.HandleListener(
		ln, netpoll.EventRead|netpoll.EventOneShot,
	))
here on Must panics

on regular sockets works, but on ssl did not manage to make it work in any way :(

tried different methods to get underlying net.Conn in order for File() reflection to work but did not manage to make it happen and could not find single example of this being used 

Is this even possible ?

**Comment by gobwas** [comment]
Hi @pokerman79!

Yeah, it is nevermind what layering you use over TCP sockets.
You can try to first listen tcp via `net.Listen("tcp", ...)`, then register sockets within netpoll, and then wrap accepted conn with tls appropriate methods (like `tls.Server()`).
