### ISSUE TITLE
detect client disconnect

### ISSUE THREAD

**Issue by vtolstov** [gobwas/ws#65]
i have server, that spawns some external binary and send output to client via websocket.
I'm not read any input from user because external program non-interactive.

How can i detect that user disconnects and stop sending data? naive http handler (skip upgrade part)
```
   ww := wsutil.NewWriterSize(conn, ws.StateServerSide, ws.OpBinary, 1024)
   cmd := exec.Command("dmesg", "--color=always", "-w")
   cmd.Env = []string{
     "TERM", "xterm-256color",
   }
   ptmx, err := pty.Start(cmd)
   if err != nil {
     log.Printf("%v", err)
     return
   }
   defer ptmx.Close()
   defer cmd.Process.Kill()
   wr := bufio.NewReaderSize(ptmx, 1024)
   for {
     line, err := wr.ReadSlice('\n')
     if err != nil {
       log.Printf("%v\n", err)
       return
     }
     _, err = ww.Write(line)
     if err == nil {
       err = ww.Flush()
     }
     if err != nil {
       log.Printf("%v", err)
       return
     }
   }
```

**Comment by gobwas** [comment]
Hello!

So, am I understand it right, that `conn` is a tcp socket?
Thus, it depends on how client closes its connections – if it does just `tcpconn.Close()` (say, linux `close()` syscall), then you will receive error on your further `Write()` call. If client closes its connection gracefully with `tcpconn.CloseWrite()` (say, linux `shutdown()` syscall), then your `Write()` will still receive no error. Furthermore, if you doing your `Write()` calls not so frequently, even if client did `close()`, your socket will be active until you prepare next `Write()` call.

So my suggestion is to use additional goroutine that reads, say, 1 byte from client connection and when it returns io.EOF it means that client gone somehow. After that you could stop reading from `ptmx` (for example by killing spawned cmd) and return from the main loop.

**Comment by vtolstov** [comment]
if client does not send any data (only read from socket), what returns when i'm try to read 1 byte from conn?

**Comment by vtolstov** [comment]
thanks! i'm try to integrate ping/pong

**Comment by jjhesk** [comment]
if that closes automatically by receiving 1005 from ws. should i still prepare to make ping pong message too?
