### ISSUE TITLE
How should i deal with message fragmentation?

### ISSUE THREAD

**Issue by tema3210** [gobwas/ws#66]
Hello,for my project i using websockets and protobuf,so the problem is the protobuf's messages isn't self-describing i have to send plain `[]byte`,but your library even with `wsutil` package returning opcode to me from `wsutil.ReadClientData()`, the Opcode enumerates state of current frame, the Fin byte instead indicating end of the frame, Fin usage is incapsulated by library ,but Opcode is not, as of these two are working together i have no ideas how it's supposed to work.
P.S You already have code to recieve frames and messages, why not make this func block until the message is completly arriven?

**Comment by gobwas** [comment]
Hello. Sorry, I did not understand the case. How do you send your messages? How do you read them?

**Comment by tema3210** [comment]
The problem is the ReadClientData func gives me opcode, it works in pair with fin byte but what actually the opcode you returning there does, if fin usage is incapsulated?

**Comment by tema3210** [comment]
> Hello. Sorry, I did not understand the case. How do you send your messages? How do you read them?

I'm using protobuf structures, i `Marshal()`'ing them into a plain `[]byte` array. Question is when i call  `wsutil.ReadClientData()` it among `[]byte` still gives me OpCode,what i have do with it,

**Comment by gobwas** [comment]
That `OpCode` could be either `ws.OpText` or `ws.OpBinary`. **Data** in the name of the function stands for data frames. If you want read only binary frame, you could call `wsutil.ReadClientBinary()`.
