### ISSUE TITLE
follow the rules to increase performance

### ISSUE THREAD

**Issue by jjhesk** [gobwas/ws#70]
Check it out: 
https://speakerdeck.com/eranyanay/going-infinite-handling-1m-websockets-connections-in-go

from what I understand now, there are 2 major caveats:

1. goroutines - reduce amount of goroutines from raising a new connection
2. buffer allocations - keep a reference to the underlying buffers given by Hijack()

**Comment by gobwas** [comment]
Hi @jjhesk, thank you for sharing. Just for the notice, there is an article discussing same optimizations written 2 years ago: https://medium.freecodecamp.org/million-websockets-and-go-cc58418460bb

**Comment by jjhesk** [comment]
thank you, it was really helpful. I just learned about it.

**Comment by gobwas** [comment]
@jjhesk not neccessary data race – It could be anything involved in I/O.
