### ISSUE TITLE
Dose the helper function ReadMessage() handling the fragmentation still work when using epoll?

### ISSUE THREAD

**Issue by shengxiang200788** [gobwas/ws#72]
I use epoll to watch a read event, and call Readmessage() or ReadClientData() in the readevent handler.
Will I  get the whole messages in this handler? Or I should take care of the framgmetation?

**Comment by ligser** [comment]
It should work well. Underlying readers limited to read not more bytes than presented in frame. They will not unblock until at least that bytes will be received from a `conn`. Also, all of these methods have special cases that start to read a new frame when the not final frame received. That will block the method until all the frames of the messages will be received.

**Comment by gobwas** [comment]
Thanks, @ligser 👍
