### ISSUE TITLE
Stack based slice does not work.

### ISSUE THREAD

**Issue by limpo1989** [gobwas/ws#73]
```go
func ReadHeader(r io.Reader) (h Header, err error) {
	var b [MaxHeaderSize - 2]byte

       // ************ OLD CODE (Go 1.12 does not work!) ************
	//bp := uintptr(unsafe.Pointer(&b))
	//bh := &reflect.SliceHeader{Data: bp, Len: 2, Cap: MaxHeaderSize - 2}
	//bts := *(*[]byte)(unsafe.Pointer(bh))

        // ************ NEW CODE (Go 1.12 work it!) ************
	var bts []byte
	bh := (*reflect.SliceHeader)(unsafe.Pointer(&bts))
	bh.Data = uintptr(unsafe.Pointer(&b))
	bh.Cap = MaxHeaderSize - 2
	bh.Len = 2

	// Prepare to hold first 2 bytes to choose size of next read.
	_, err = io.ReadFull(r, bts)
	if err != nil {
		return
	}
        ....
}```

**Comment by cristaloleg** [comment]
What do you mean by 'does not work`? Panic? Error? Compilation error?

**Comment by limpo1989** [comment]
> go version go1.12.4 windows/amd64  

Send a text message using a browser-based websocket.  
```
// javascript code:
var message = "Hello WebSocket";
websocket.send(JSON.stringify({"message" : message}) + "\n");
```
`ws.ReadHeader`  > `bts` variable always the initial value  
![TIM截图20190417091354](https://user-images.githubusercontent.com/4050314/56254006-84a06600-60f1-11e9-91cc-5eb81d852a59.png)

The result of modifying the `stack based slice` code.

![TIM截图20190417091430](https://user-images.githubusercontent.com/4050314/56254009-8833ed00-60f1-11e9-9772-7337a6e91d9d.png)

**Comment by gobwas** [comment]
Hi @limpo1989, looks like you are right. The docs of unsafe.Pointer suggests the same pattern. Thank you, I will fix it this week.

**Comment by gobwas** [comment]
@limpo1989 sorry for late action, here the [PR](https://github.com/gobwas/ws/pull/76).

**Comment by limpo1989** [comment]
@gobwas The issue don't be fix and low probability to SIGSEGV 
go version:  `go version go1.12.5 windows/amd64` 
go mod: `github.com/gobwas/ws v1.0.2-0.20190519195829-89d0ae05650f`
> read.go > ws.ReadHeader
> ```go
>	bh := (*reflect.SliceHeader)(unsafe.Pointer(&bts))
>	//*bh = reflect.SliceHeader{
>	//	Data: uintptr(unsafe.Pointer(&b)),
>	//	Len:  2,
>	//	Cap:  len(b),
>	//}
>
>	bh.Data = uintptr(unsafe.Pointer(&b))
>	bh.Len = 2
>	bh.Cap = len(b)
> ```

![TIM截图20190520185948](https://user-images.githubusercontent.com/4050314/58017630-443e6880-7b33-11e9-9130-8a5f53b6c744.png)

The result of modifying the stack based slice code:
![TIM截图20190520190045](https://user-images.githubusercontent.com/4050314/58017650-515b5780-7b33-11e9-8ba2-753700740be2.png)

**Comment by gobwas** [comment]
@limpo1989 but what the difference? I mean, is it just a race and your code still able to get same result (zeroed slice) or there is some compiler hint writing Data field that way? Can we reproduce this somehow by unit test?

**Comment by limpo1989** [comment]
It is not safe to pass a pointer on the stack to a syscall ([fd_windows.go:526](https://github.com/golang/go/blob/3e9d8e2e1bb94c3e302da8121f9cc018d86d1e71/src/internal/poll/fd_windows.go#L526)). The memory on the stack will be moved when the stack shrinks or expands. But the pointer held in the syscall will not be fixed, the read and write will be undefined behavior.

> 
```go
*bh = reflect.SliceHeader{
	Data: uintptr(unsafe.Pointer(&b)),
	Len:  2,
	Cap:  len(b),
}

$ go build -gcflags '-m -l' unsafe.go
# command-line-arguments
.\unsafe.go:68:17: leaking param: r
.\unsafe.go:84:46: ReadHeader &bts does not escape
.\unsafe.go:86:32: ReadHeader &b does not escape
.\unsafe.go:95:53: ReadHeader &b does not escape
...

```
```go
bh.Data= uintptr(unsafe.Pointer(&b))
bh.Len=  2
bh.Cap=  len(b)

$ go build -gcflags '-m -l' unsafe.go
# command-line-arguments
.\unsafe.go:91:34: &b escapes to heap
.\unsafe.go:81:3: moved to heap: b
...
```

**Comment by limpo1989** [comment]
Unable to reproduce in unit test, because the stack shrink or expansion can not be well controlled, but in my project can be 100% recurring, the following is my screenshot, you can see the memory address is moved, but the data It will still be written to the memory before the move.

![20190523101517](https://user-images.githubusercontent.com/4050314/58221191-3d3a7480-7d44-11e9-85b6-13a399bb5eca.png)

**Comment by gobwas** [comment]
Hi @limpo1989,

I started to try to figure it out on the windows and wrote a test which grows stack until `morestack` is called and then prepares read on the *unsafe-crafted* slice of bytes. Currently it works well on both Linux and Windows, but I will try to dig dipper and write same test for concurrent reads from, say, file or something which involves a system call.

If you have any ideas how to catch this bug let me know.

Also, as you said:
> But the pointer held in the syscall will not be fixed, the read and write will be undefined behavior.

Regarding the source code, I see that `o.Init(buf)` is just saving a pointer to the given buffer, which underlying `Data` field shoud be updated if the stack moves. Does syscall itself leads to stack move **after** storing pointer?

**Comment by gobwas** [comment]
Also, could you try to add `//go:nosplit` directive above the `ReadHeader()` function to check does this problem really relate to stack moving?

**Comment by gobwas** [comment]
Currently I am able to reproduce this:
<img width="792" alt="Screenshot 2019-05-25 23 18 43" src="https://user-images.githubusercontent.com/675117/58374236-a20fed80-7f43-11e9-9162-69d13dbc9150.png">
