### ISSUE TITLE
Is there any thing like gorilla/websocket func (c *Conn) SetReadLimit(limit int64)

### ISSUE THREAD

**Issue by rangercyh** [gobwas/ws#74]
when I change from gorilla/websocket to gobwas/ws. I found SetReadLimit() in gorilla/websocket to limit then max size of text or binary frame size, but I found nothing in gobwas/ws like that.

I check the code in gorilla/websocket:

https://github.com/gorilla/websocket/blob/80c2d40e9b91f2ef7a9c1a403aeec64d1b89a9a6/conn.go#L859-L870

I check wsutil code:

https://github.com/gobwas/ws/blob/7338e265e1ab4ea2403da5ce80d934ef5f976923/wsutil/reader.go#L171-L194

likely nothing to limit the size of a frame, so Is there anything about that requirement or could you give me some tips for doing that.

thx~

**Comment by nerg4l** [comment]
Can't you just wrap the reader (conn)?

```go
// Modified version of io.LimitedReader
//
// A LimitedReader reads from R but limits the amount of
// data returned to just N bytes. Each call to Read
// updates N to reflect the new amount remaining.
// Read returns ErrExceededLimit when N <= 0 and EOF when the underlying R returns EOF.
type LimitedReader struct {
	R io.Reader // underlying reader
	N int64  // max bytes remaining
}

func (l *LimitedReader) Read(p []byte) (n int, err error) {
	if l.N <= 0 {
		return 0, ErrExceededLimit // This line is different from io.LimitReader
	}
	if int64(len(p)) > l.N {
		p = p[0:l.N]
	}
	n, err = l.R.Read(p)
	l.N -= int64(n)
	return
}

// [...]
	h, err := conn.NextFrame()
	if err != nil {
		return
	}

	bytes, err := ioutil.ReadAll(&LimitedReader{conn, maxMessageSize})
	if err != nil {
		return // err will be ErrExceededLimit if the message is over limit
	}
// [...]
```

**Comment by rangercyh** [comment]
> Can't you just wrap the reader (conn)?
> 
> ```go
> // Modified version of io.LimitedReader
> //
> // A LimitedReader reads from R but limits the amount of
> // data returned to just N bytes. Each call to Read
> // updates N to reflect the new amount remaining.
> // Read returns ErrExceededLimit when N <= 0 and EOF when the underlying R returns EOF.
> type LimitedReader struct {
> 	R io.Reader // underlying reader
> 	N int64  // max bytes remaining
> }
> 
> func (l *LimitedReader) Read(p []byte) (n int, err error) {
> 	if l.N <= 0 {
> 		return 0, ErrExceededLimit // This line is different from io.LimitReader
> 	}
> 	if int64(len(p)) > l.N {
> 		p = p[0:l.N]
> 	}
> 	n, err = l.R.Read(p)
> 	l.N -= int64(n)
> 	return
> }
> 
> // [...]
> 	h, err := conn.NextFrame()
> 	if err != nil {
> 		return
> 	}
> 
> 	bytes, err := ioutil.ReadAll(&LimitedReader{conn, maxMessageSize})
> 	if err != nil {
> 		return // err will be ErrExceededLimit if the message is over limit
> 	}
> // [...]
> ```

yes, thank you for that. I have read golang/src/io.go and found io.LimitedReader, when the msg is above the limit it return EOF, your wraper is more sensible.

**Comment by nerg4l** [comment]
The other solution would be to use a buffer with a fixed size.

```go
// readMax reads from r until an error, EOF or capacity reached
// and returns the data it read from the internal buffer allocated
// with a specified capacity.
func readMax(r io.Reader, capacity int64) (b []byte, err error) {
	buf := make([]byte, capacity)
	n, err := r.Read(buf)
	if err == io.EOF {
		return buf[:n], nil
	}
	if err != nil {
		return nil, err
	}
	return nil, io.ErrUnexpectedEOF
}
```

**Comment by nerg4l** [comment]
Also there is a todo
https://github.com/gobwas/ws/blob/7338e265e1ab4ea2403da5ce80d934ef5f976923/wsutil/reader.go#L40

**Comment by rangercyh** [comment]
> The other solution would be to use a buffer with a fixed size.
> 
> ```go
> // readAllWithLimit reads from r until an error, EOF or limit reached
> // and returns the data it read from the internal buffer allocated
> // with a specified capacity.
> func readAllWithLimit(r io.Reader, limit int64) (b []byte, err error) {
> 	buf := make([]byte, limit)
> 	n, err := r.Read(buf)
> 	if err == io.EOF {
> 		return buf[:n], nil
> 	}
> 	if err != nil {
> 		return nil, err
> 	}
> 	return nil, ErrExceededLimit
> }
> ```
> 
> Edit: Changed the naming of the fictional method and its attributes.

I am using io.Reader for translate a websocket data to a tcp socket, so my code like that:

```go
func (b *Bridge) Forward() error {
    b.io.Lock()
    defer b.io.Unlock()

    h, r, err := wsutil.NextReader(b.client_conn, ws.StateServerSide)
    if err != nil {
        log.Printf("%s client conn read error: %v", b.client_name, err)
        return err
    }
    if h.OpCode.IsControl() {
        err = wsutil.ControlFrameHandler(b.client_conn, ws.StateServerSide)(h, r)
        if err != nil {
            log.Printf("%s client conn control process error: %v", b.client_name, err)
        }
        return err
    }
    lr := LimitReader(r, *max_read_size)
    if _, err = io.Copy(b.server_conn, lr); err != nil {
        log.Printf("%s forward copy error: %v", b.client_name, err)
        return err
    }

    return nil
}
```

using your LimitedReader is perfect! thx~

**Comment by nerg4l** [comment]
Forget my previous answers. I just realised that it can be done much easier.

```
func (b *Bridge) Forward() error {
    // [...]
    h, r, err := wsutil.NextReader(b.client_conn, ws.StateServerSide)
    // [...]
    // h.Lenght contains the length of the frame
    if h.Length > *max_read_size {
        return ErrExceededHardLimit // your error
    }
    // [...]
}
```

This way you can exit before starting the copy.

**Comment by rangercyh** [comment]
> Forget my previous answers. I just realised that it can be done much easier.
> 
> ```go
> func (b *Bridge) Forward() error {
>     // [...]
>     h, r, err := wsutil.NextReader(b.client_conn, ws.StateServerSide)
>     // [...]
>     // h.Lenght contains the length of the frame
>     if h.Length > *max_read_size {
>         return ErrExceededHardLimit // your error
>     }
>     // [...]
> }
> ```
> 
> This way you can exit before starting the copy.

e..... I have no idea about that before. your code just look amazing.... I will change to it. thx again...
