### ISSUE TITLE
when put ws server under nginx, client request throw  505 error?

### ISSUE THREAD

**Issue by coanor** [gobwas/ws#75]
I start the ws at `ws://localhost:9628/v1/ws/agent`, when connect directly with following client code, it works ok: 

    url := `ws://localhost:9628/v1/ws/agent`
    conn, _, _, err := ws.DefaultDialer.Dial(context.Background(), url)
    if err != nil {
        log.Fatal(err) 
    }

But when I put the server as a Nginx (Version: `nginx/1.4.6 (Ubuntu)`) upstream, and connect `ws://localhost:80/v1/ws/agent`:

    server {
        listen 80;
        location /v1/ws/agent {
            proxy_pass http://localhost:9628;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'Upgrade';
        }
    }

The error says that "unexpected HTTP response status: 505". Why this happend?

**Comment by ianic** [comment]
I'm also using Nginx in front of gobwas/ws server with the same configuration.
Try to change proxy_pass line to:
`proxy_pass http://localhost:9628/v1/ws/agent;`
if you have something else at the root url.

**Comment by nerg4l** [comment]
HTTP upgrade only supported from version 1.1. More details on that [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Protocol_upgrade_mechanism).

The default value of `proxy_http_version` is `1.0` according to the (NginX documentation)[http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_http_version].

So by adding `proxy_http_version 1.1;` it should work.

```
server {
    listen 80;
    location /v1/ws/agent {
        proxy_pass http://localhost:9628;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'Upgrade';
    }
}
```

Nginx has a great (NGINX as a WebSocket Proxy article)[https://www.nginx.com/blog/websocket-nginx/].

**Comment by gobwas** [comment]
Thanks, guys! 
@coanor could I close this?
