### ISSUE TITLE
How to detect idle connection?

### ISSUE THREAD

**Issue by ehsannm** [gobwas/ws#83]
Hi,

We are using gobwas/ws in our production server. We have a pool of go routines which will be called on Desc events. The problem is that the only way to detect idle connections is to have a separate routine check connections and close them if needed. 

I was wondering if it is the  correct way to handle this problem or is there any better solution on this?

**Comment by navossoc** [comment]
I can think a few ways:

https://golang.org/pkg/net/#TCPConn.SetKeepAlive
https://golang.org/pkg/net/#TCPConn.SetKeepAlivePeriod

https://golang.org/pkg/net/#TCPConn.SetDeadline
https://golang.org/pkg/net/#TCPConn.SetReadDeadline
https://golang.org/pkg/net/#TCPConn.SetWriteDeadline

https://godoc.org/github.com/gobwas/ws#NewPingFrame
https://godoc.org/github.com/gobwas/ws#NewPongFrame

https://godoc.org/github.com/gobwas/ws/wsutil#ControlHandler.HandlePing
https://godoc.org/github.com/gobwas/ws/wsutil#ControlHandler.HandlePong

Not sure which one will be more suited to you...

**Comment by KromDaniel** [comment]
If you're ok to work only with linux you can use epoll

see example number 4
https://github.com/eranyanay/1m-go-websockets

If you want it to be cross platform use libuv like libraries for go

**Comment by ehsannm** [comment]
@KromDaniel the problem is we don't receive close signal from the other side, we have many stalled connections which we dont receive any event for a long period, and for now we have a GC to detect those connections and close them, but i was wondering why just SetDeadline is not working on the connections with netpoll.Desc attached.

**Comment by gobwas** [comment]
Closing this for now, please reopen if question is still active.

**Comment by hxt365** [comment]
Hi, have you got a desire solution? if yes, can you share?

**Comment by ehsannm** [comment]
@hxt365 we implemented a watch dog mechanism with an in-memory cache to monitor idle connections and close them.
Briefly, On each request received we update timestamp for that descriptor and a garbage collector to close the idle connection.
