### ISSUE TITLE
[Community] Users

### ISSUE THREAD

**Issue by kataras** [gobwas/ws#84]
Hello @gobwas, it would be a great idea to fill the [wiki pages](https://github.com/gobwas/ws/wiki) or the `README.md` and provide a `Users` section which other authors can link their projects or companies working on and using this package.

A good user example is the [neffos real-time framework](https://github.com/kataras/neffos).

**Comment by gobwas** [comment]
Hi @kataras, but Im actually don't know how much users are really ready to share this information?
Even due to the security reasons – if someone discovers bug here it would be much easier to explot it.

**Comment by kataras** [comment]
I see, in [iris](https://github.com/kataras/iris) we don't publish that kind of information for security reasons too. Got it. Thank you.
