### ISSUE TITLE
Read a ping message from client

### ISSUE THREAD

**Issue by ramvasanth** [gobwas/ws#86]
How do i read ping control message that comes from client and send a pong message. currently
i am using `c.ws.ReadMessage()`, i dont know how to read the ping control message so that i can send pong message

**Comment by navossoc** [comment]
You can take a look at [wsutil.ReadClientText](https://godoc.org/github.com/gobwas/ws/wsutil#ReadClientText)

Which goes down to `wsutil.readData` that handles control messages, so you can check it how it is done.
https://github.com/gobwas/ws/blob/05baaea2bbcfe8963301c62d9931c882d59595cd/wsutil/helper.go#L262

If you don't need to inspect the data from the ping message, you can let it handle it automatically.

[]'s

**Comment by ramvasanth** [comment]
@navossoc  , i want to find out if the current message is control message and then let it handle it automatically and immediately return without waiting for next frame.
the reason is that we are using linux epool,   it wakes up the connection for control message and endlessly wait

**Comment by ramvasanth** [comment]
`wsutil.ReadClientText(conn)` this blocks whe epool wakes up this connnection, we want it to exit if the message is control

**Comment by ramvasanth** [comment]
can we propose the following solution:

when the message is control message , send the control message and then return to caller without having to wait for text message.

change the this 			continue to

return nil, controlCode, nil

**Comment by gobwas** [comment]
Why use `readData()` for such case? Why not `ReadMessage()` or even `ws.ReadHeader()` and then handle frames manually?
