### ISSUE TITLE
Feature request - close frame with reason string

### ISSUE THREAD

**Issue by KromDaniel** [gobwas/ws#94]
As defined in the protocol (please correct me if I'm wrong)
close frame may come with status code and a reason

The current situation is that 

(wsutil/handler.go)
```go
func (c ControlHandler) HandleClose(h ws.Header) error
``` 

will only send the status code without the reason string (and it's ok, since it's part of the protocol)

however, close frame may also contain reason string, which is already defined here:

(check.go)

```go
ErrProtocolOpCodeReserved             = ProtocolError("use of reserved op code")
ErrProtocolControlPayloadOverflow     = ProtocolError("control frame payload limit exceeded")
ErrProtocolControlNotFinal            = ProtocolError("control frame is not final")
ErrProtocolNonZeroRsv                 = ProtocolError("non-zero rsv bits with no extension negotiated")
ErrProtocolMaskRequired               = ProtocolError("frames from client to server must be masked")
ErrProtocolMaskUnexpected             = ProtocolError("frames from server to client must be not masked")
ErrProtocolContinuationExpected       = ProtocolError("unexpected non-continuation data frame")
ErrProtocolContinuationUnexpected     = ProtocolError("unexpected continuation data frame")
ErrProtocolStatusCodeNotInUse         = ProtocolError("status code is not in use")
ErrProtocolStatusCodeApplicationLevel = ProtocolError("status code is only application level")
ErrProtocolStatusCodeNoMeaning        = ProtocolError("status code has no meaning yet")
ErrProtocolStatusCodeUnknown          = ProtocolError("status code is not defined in spec")
ErrProtocolInvalidUTF8                = ProtocolError("invalid utf8 sequence in close reason")
```

I encountered  a problem that there's a WS client (Poco) that might be have issue if it doesn't receive reason string with the close frame, even that it is valid by the protocol

Is it possible to add it? 
I can help with a PR if you need, just want to make sure I'm not missing something with the protocol, or missing that there's already existing options to do that

**Comment by gobwas** [comment]
Hello @KromDaniel,

Sorry for a one year delay! 😄 
If it's still active, please reopen it.

It's not much clear for me how errors from check.go are related to the close reason?
`HandleClose()` handles close frame came from the peer. If it contain some reason, it is returned to the `HandleClose()` caller inside the `ClosedError` error. As [RFC](https://tools.ietf.org/html/rfc6455#section-5.5.1) states:
> If an endpoint receives a Close frame and did not previously send a
   Close frame, the endpoint MUST send a Close frame in response.  (When
   sending a Close frame in response, the endpoint typically echos the
   status code it received.)  It SHOULD do so as soon as practical.  An
   endpoint MAY delay sending a Close frame until its current message is
   sent (for instance, if the majority of a fragmented message is
   already sent, an endpoint MAY send the remaining fragments before
   sending a Close frame).  However, there is no guarantee that the
   endpoint that has already sent a Close frame will continue to process
   data.

So does Poco really expects reason even for sent-back close frames?

**Comment by KromDaniel** [comment]
Yea the check.go as close reason was a bad example.

However, gobwas is indeed compliant to the protocol and the issue is with [Poco](https://pocoproject.org/) library. Anyway this can be achieved by manually calling 

```go
f := ws.NewCloseFrame(ws.NewCloseFrameBody(code, reason))
ws.WriteFrame(conn, f)
```

So thanks anyway @gobwas !

**Comment by gobwas** [comment]
Probably yeah. I can think about adding a callback to the CloseHandler struct which will optionally map received error frame code&reason to one that will be sent in turn. Do you find it useful?

**Comment by gobwas** [comment]
I'm going to close this, since it's too old and seems that not so urgent :D 
Plese, reopen if it's needed.

**Comment by KromDaniel** [comment]
Sorry for never answering your question :(
Indeed issue is no longer an issue

Thanks a lot! :)

**Comment by gobwas** [comment]
@KromDaniel no problem at all! Cheers!
