### ISSUE TITLE
hope can support go mod 

### ISSUE THREAD

**Issue by cclehui** [gobwas/ws#95]
as go mod  use more and more ?  can we support it ?

**Comment by cristaloleg** [comment]
Sounds like a goal for `v2` (to not break anything)

**Comment by gobwas** [comment]
@cristaloleg Will we break anything if I will just add it in next release when wsflate get merged?

**Comment by PaluMacil** [comment]
I don't know what it would possibly break. I think it would be fine to use go mod now. If you were already v2+, you'd need to make some careful decisions, but as it is, you just need a go.mod file with your dependencies and a tagged release.

**Comment by gobwas** [comment]
Yup, I think same. I added go.mod already in v1.1.0-rc.1 release.

**Comment by gobwas** [comment]
Closing this for now.
