### ISSUE TITLE
Using for client side

### ISSUE THREAD

**Issue by tech-a-go-go** [gobwas/ws#96]
Hi there,

I'm thinking to use gobwas/ws for **client side** to improve performance.

Can I still get the following benefits by using gobwas/ws as a websocket client instead of gorilla/websocket ?

* Zero-copy upgrade
* No intermediate allocations during I/O
* Low-level API which allows to build your own logic of packet handling and buffers reuse
* High-level wrappers and helpers around API in wsutil package, which allow to start fast without digging the protocol internals

Thank you.

**Comment by gobwas** [comment]
Hey @tech-a-go-go ,

Sorry for silence.

Yes, for sure you can use them as well.
